version: "3"

networks:
  dbnet:
    driver: bridge

services:
  pgserver:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: pgserver
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - dbnet
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped

volumes:
  postgres-data:
